[package]
name = "rustique"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.21.1", default-features = false }

[dependencies]
